name: text
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.0-19.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_lints: ^2.0.0
  provider: ^6.0.2


  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.3


  firebase_core:
  firebase_auth:
  cloud_firestore:


  shared_preferences: ^2.0.15
  bottom_nav_bar: ^1.0.3

dev_dependencies:
  build_runner: ^2.0.6
  hive_generator: ^1.1.3
  flutter_launcher_icons: ^0.11.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/imgs/AppLogo.png"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/imgs/Prod1.png
    - assets/imgs/Nintendo Gameqube.jpg
    - assets/imgs/Ps 2.jpg
    - assets/imgs/GD Emu.png
    - assets/imgs/Sega Dreamcast(Jap).jpg
    - assets/imgs/Sega Dreamcast(Eu).jpg
    - assets/imgs/AppLogo.png
    - assets/imgs/AvBackImg.jpg
    - assets/imgs/backImg.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono-Bold.ttf
        - asset: assets/fonts/JetBrainsMono-Medium.ttf
        - asset: assets/fonts/JetBrainsMonoNL-Medium.ttf
    - family: FiraCode
      fonts:
        - asset: assets/fonts/FiraCode-Medium.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
